version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: SQLServerPassword123@
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
  adminer:
    image: adminer
    ports:
      - 8080:8080
  
volumes:
  sql_data: